spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/bsep
spring.datasource.username=postgres
spring.datasource.password=super
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bsepteam6@gmail.com
spring.mail.password=${MAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=team6.bsep@gmail.com

#adminisration
app.seed.admin.email=admin@bsep.local
app.seed.admin.password=${APP_SEED_ADMIN_PASSWORD:}
app.seed.admin.first-name=System
app.seed.admin.last-name=Administrator
app.seed.admin.organization=BSEP



