spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/bsep
spring.datasource.username=postgres
spring.datasource.password=super
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bsepteam6@gmail.com
spring.mail.password=${MAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=team6.bsep@gmail.com

jwt.secret=/wa4JtaVB6qn3hNUCyBYRjKw1qCKoyeZCuNiVsNfDh4tknZS45kVYlBej/pWr61CXyNBzFv2aQXglCVNXoqj+A==
jwt.expires-in=1800000
google.recaptcha.secret=6LebrccrAAAAAASF0qgvrcW32gQfdadzP7FaWh2B

#adminisration
# email sam izmenila tj. dodala @example.com jer login forma zahteva da bude bas email...
app.seed.admin.email=admin@example.com
app.seed.admin.password=${APP_SEED_ADMIN_PASSWORD}
app.seed.admin.first-name=System
app.seed.admin.last-name=Administrator
app.seed.admin.organization=BSEP

#CA certificates
app.ca.root.subject=CN=BSEP Root CA, O=BSEP, C=RS
app.ca.root.key-size=4096
app.ca.root.validity-days=3650
app.ca.root.sig-alg=SHA256withRSA
app.ca.root.path-len=1
app.ca.root.keystore-path=./data/keystores/root-ca.p12
app.ca.root.keystore-alias=rootca

app.crypto.kek=${APP_CRYPTO_KEK}
app.ca.root.auto-create=true

application.properties: spring.profiles.active=dev
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true




